Adjust init.d supervisor script to start a particular celery environment

diff --git a/scripts/celeryconf/supervisord.initd b/scripts/celeryconf/supervisord.initd
--- a/scripts/celeryconf/supervisord.initd
+++ b/scripts/celeryconf/supervisord.initd
@@ -9,10 +9,22 @@ SUPERVISORD=/usr/bin/supervisord
 SUPERVISORCTL=/usr/bin/supervisorctl
 CONFIG=/home/ec2-user/pinpoint/env/SecondFunnel/scripts/celeryconf/supervisord.conf
 
+E_BADARGS=85
+
 case $1 in
 start)
         echo -n "Starting supervisord: "
         sudo $SUPERVISORD -c $CONFIG
+        if [ "$2" = "test" ]; then
+            echo -n "Starting within test environment"
+            sudo $SUPERVISORCTL -c $CONFIG start celery_test
+        elif [ "$2" = "production" ]; then
+            echo -n "Starting within production environment"
+            sudo $SUPERVISORCTL -c $CONFIG start celery_production
+        else
+            echo "Missing environment name. Must be 'test' or 'production'."
+            exit $E_BADARGS
+        fi
         echo
         ;;
 stop)
